/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface RaffleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkUpkeep"
      | "enterRaffle"
      | "getEntranceFee"
      | "getInterval"
      | "getLatestTimeStamp"
      | "getNumWords"
      | "getNumberOfPlayers"
      | "getPlayer"
      | "getRaffleState"
      | "getRecentWinner"
      | "getRequestConfirmation"
      | "performUpkeep"
      | "rawFulfillRandomWords"
      | "requestRandommWinner"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RaffleEnter"
      | "RequestedRaffleWinner"
      | "WinnerPicked"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "checkUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "enterRaffle",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEntranceFee",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getInterval",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLatestTimeStamp",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumWords",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getNumberOfPlayers",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPlayer",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRaffleState",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRecentWinner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRequestConfirmation",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "performUpkeep",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "rawFulfillRandomWords",
    values: [BigNumberish, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "requestRandommWinner",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "checkUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "enterRaffle",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEntranceFee",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getInterval",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getLatestTimeStamp",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNumberOfPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPlayer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getRaffleState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecentWinner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRequestConfirmation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "performUpkeep",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "rawFulfillRandomWords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "requestRandommWinner",
    data: BytesLike
  ): Result;
}

export namespace RaffleEnterEvent {
  export type InputTuple = [player: AddressLike];
  export type OutputTuple = [player: string];
  export interface OutputObject {
    player: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RequestedRaffleWinnerEvent {
  export type InputTuple = [requestedId: BigNumberish];
  export type OutputTuple = [requestedId: bigint];
  export interface OutputObject {
    requestedId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace WinnerPickedEvent {
  export type InputTuple = [winner: AddressLike];
  export type OutputTuple = [winner: string];
  export interface OutputObject {
    winner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Raffle extends BaseContract {
  connect(runner?: ContractRunner | null): Raffle;
  waitForDeployment(): Promise<this>;

  interface: RaffleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkUpkeep: TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean }],
    "nonpayable"
  >;

  enterRaffle: TypedContractMethod<[], [void], "payable">;

  getEntranceFee: TypedContractMethod<[], [bigint], "view">;

  getInterval: TypedContractMethod<[], [bigint], "view">;

  getLatestTimeStamp: TypedContractMethod<[], [bigint], "view">;

  getNumWords: TypedContractMethod<[], [bigint], "view">;

  getNumberOfPlayers: TypedContractMethod<[], [bigint], "view">;

  getPlayer: TypedContractMethod<[index: BigNumberish], [string], "view">;

  getRaffleState: TypedContractMethod<[], [bigint], "view">;

  getRecentWinner: TypedContractMethod<[], [string], "view">;

  getRequestConfirmation: TypedContractMethod<[], [bigint], "view">;

  performUpkeep: TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;

  rawFulfillRandomWords: TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  requestRandommWinner: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkUpkeep"
  ): TypedContractMethod<
    [arg0: BytesLike],
    [[boolean, string] & { upkeepNeeded: boolean }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "enterRaffle"
  ): TypedContractMethod<[], [void], "payable">;
  getFunction(
    nameOrSignature: "getEntranceFee"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getInterval"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLatestTimeStamp"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNumWords"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getNumberOfPlayers"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPlayer"
  ): TypedContractMethod<[index: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRaffleState"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRecentWinner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getRequestConfirmation"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "performUpkeep"
  ): TypedContractMethod<[arg0: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "rawFulfillRandomWords"
  ): TypedContractMethod<
    [requestId: BigNumberish, randomWords: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "requestRandommWinner"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "RaffleEnter"
  ): TypedContractEvent<
    RaffleEnterEvent.InputTuple,
    RaffleEnterEvent.OutputTuple,
    RaffleEnterEvent.OutputObject
  >;
  getEvent(
    key: "RequestedRaffleWinner"
  ): TypedContractEvent<
    RequestedRaffleWinnerEvent.InputTuple,
    RequestedRaffleWinnerEvent.OutputTuple,
    RequestedRaffleWinnerEvent.OutputObject
  >;
  getEvent(
    key: "WinnerPicked"
  ): TypedContractEvent<
    WinnerPickedEvent.InputTuple,
    WinnerPickedEvent.OutputTuple,
    WinnerPickedEvent.OutputObject
  >;

  filters: {
    "RaffleEnter(address)": TypedContractEvent<
      RaffleEnterEvent.InputTuple,
      RaffleEnterEvent.OutputTuple,
      RaffleEnterEvent.OutputObject
    >;
    RaffleEnter: TypedContractEvent<
      RaffleEnterEvent.InputTuple,
      RaffleEnterEvent.OutputTuple,
      RaffleEnterEvent.OutputObject
    >;

    "RequestedRaffleWinner(uint256)": TypedContractEvent<
      RequestedRaffleWinnerEvent.InputTuple,
      RequestedRaffleWinnerEvent.OutputTuple,
      RequestedRaffleWinnerEvent.OutputObject
    >;
    RequestedRaffleWinner: TypedContractEvent<
      RequestedRaffleWinnerEvent.InputTuple,
      RequestedRaffleWinnerEvent.OutputTuple,
      RequestedRaffleWinnerEvent.OutputObject
    >;

    "WinnerPicked(address)": TypedContractEvent<
      WinnerPickedEvent.InputTuple,
      WinnerPickedEvent.OutputTuple,
      WinnerPickedEvent.OutputObject
    >;
    WinnerPicked: TypedContractEvent<
      WinnerPickedEvent.InputTuple,
      WinnerPickedEvent.OutputTuple,
      WinnerPickedEvent.OutputObject
    >;
  };
}
